apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-advanced-app-deployment
spec:
  replicas: 2

  selector:
    matchLabels:
      app: nodejs-advanced-app-deployment

  template:
    metadata:
      labels:
        app: nodejs-advanced-app-deployment
    spec:
      containers:
      - name: nodejs-app-c
        image: bhavin1099/nodejs-advanced-app:v2
        ports:
        - containerPort: 3000

        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: PORT

        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: REDIS_HOST

        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef: 
              name: my-config
              key: REDIS_PORT

        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NODE_ENV

      - name: redis-c
        image: redis:latest
        ports:
        - containerPort: 6379