apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-nginx
spec:
  selector:
    app: nginx
  type:  LoadBalancer
  ports:
  - name: loadbalancer-nginx
    port:  80
    targetPort:  80
# To expose loadbalancer externla ip you have to create this service in cloud platform like azure, aws vm.