apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: nodeport-port
    port:  80  # Service port
    targetPort:  80  # container port
    nodePort: 30000