# apiVersion: v1

# kind: Service

# metadata:
#   name: nodejs-advanced-app-service

# spec:
#   selector:
#     app: nodejs-advanced-app

#   type:  LoadBalancer

#   ports:
#   - protocol: TCP
#     port:  80
#     targetPort: 3000

apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app   # ✅ match with Deployment
  type: LoadBalancer   # or NodePort if LoadBalancer not supported
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
